import React from "react";
import { useState, useEffect } from "react";
import api from "../Helper/Api";
import Event from "../data/event";

const Briefing = () => {
  const [date, setDate] = useState("");
  const [answer, setAnswer] = useState(null);
  const [loading, setLoading] = useState(false);

  const getSummery = async () => {
    try {
      setLoading(true);

      const res = await api.post("/ai", {
        message: `Generate a complete morning briefing from the provided events.

                Rules:
                1. Mention ALL important events.
                2. Include low, medium, and high severity incidents.
                3. Mention harmless/resolved events separately.
                4. Cover every zone/location involved.
                5. Summarize timeline in order.
                6. Return concise professional summary.
                7. Tell me what event should be resolved first in bold letters then give me orderwise others
                `,
        events: Event[0].events,
      });

      setAnswer(res.data);
    } catch (error) {
      console.log(error);

      setAnswer("Try again...");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    const updateDate = () => {
      const now = new Date();

      const formattedDate = now.toLocaleDateString("en-US", {
        month: "long",
        day: "numeric",
        year: "numeric",
      });

      setDate(formattedDate);
    };

    updateDate();
    getSummery();
  }, []);

  //   Event
  const events = Event[0].events;
  const totalEvents = events.length;
  const criticalCount = events.filter(
    (item) => item.severity === "high",
  ).length;

  const unresolvedCount = events.filter(
    (item) => item.severity === "high" || item.severity === "medium",
  ).length;

  const badgeFailures = events.filter(
    (item) => item.type === "badge_swipe",
  ).length;

  // For Recommendations
  const actions = [];

  events.forEach((item) => {
    if (item.type === "fence_alert") {
      actions.push("Inspect Gate 3 fence sensor");
    }

    if (item.type === "vehicle_path") {
      actions.push("Review Block C vehicle access logs");
    }

    if (item.type === "badge_swipe") {
      actions.push("Verify employee E-142 credentials");
    }

    if (item.type === "accident") {
      actions.push("Investigate Block F collision immediately");
    }

    if (item.type === "drone_patrol") {
      actions.push("Archive drone patrol footage");
    }
  });

  const uniqueActions = [...new Set(actions)];

  return (
    <div className="min-h-screen bg-[#050816] text-white p-6">
      {/* Heading */}
      <div className="mb-6">
        <h1 className="text-4xl font-bold tracking-wide">
          Morning Briefing
          <span className="text-cyan-400"> — {date}</span>
        </h1>

        <p className="text-gray-400 mt-2">
          Overnight shift 00:00–06:10 • Auto-generated by 6:10 AI
        </p>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-4 gap-4 mb-6">
        <div className="bg-[#0B1120] border border-cyan-900/30 rounded-2xl p-5">
          <p className="text-xs text-gray-400 uppercase">Total Events</p>
          <h2 className="text-4xl font-bold mt-2">{totalEvents}</h2>
        </div>

        <div className="bg-[#0B1120] border border-cyan-900/30 rounded-2xl p-5">
          <p className="text-xs text-gray-400 uppercase">Critical</p>
          <h2 className="text-4xl font-bold mt-2 text-red-400">
            {criticalCount}
          </h2>
        </div>

        <div className="bg-[#0B1120] border border-cyan-900/30 rounded-2xl p-5">
          <p className="text-xs text-gray-400 uppercase">Unresolved</p>
          <h2 className="text-4xl font-bold mt-2 text-yellow-400">
            {unresolvedCount}
          </h2>
        </div>
      </div>

      {/* Main Grid */}
      <div className="grid grid-cols-12 gap-6">
        {/* Left Column */}
        <div className="col-span-8 space-y-9">
          {/* Executive Summary */}
          <div className="bg-[#0B1120] border border-cyan-900/30 rounded-2xl p-6">
            <h2 className="text-2xl font-bold text-cyan-400 mb-4">
              Executive Summary
            </h2>

            <p className="text-gray-300 leading-8">
              {loading
                ? "Generating morning briefing..."
                : answer?.summary || "No summary available."}
            </p>
          </div>
        </div>

        {/* Right Column */}
        <div className="col-span-4 space-y-9">
          {/* Recommended Actions */}
          <div className="bg-[#0B1120] border border-cyan-900/30 rounded-2xl p-6">
            <h2 className="text-xl font-bold text-cyan-400 mb-4">
              Recommended Actions
            </h2>

            <ul className="space-y-3 text-gray-300">
              {uniqueActions.map((action, index) => (
                <li key={index}>• {action}</li>
              ))}
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Briefing;
